/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.6.17 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('1','收银机账户','CASH_MACHINE','CASH','0.00','RMB','收银机现金入账部分','0.00','0.00','Y',NULL,'2798','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('4','饿了么总账户','ELE','VIRTUAL','0.00','RMB','饿了么总账户金额','0.00','0.00','Y',NULL,'4194','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('5','饿了么活动补贴账户','ALLOWANCE_ELE','VIRTUAL','0.00','RMB','饿了么平台返还给商家的补贴部分','0.00','0.00',NULL,'4','1705','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('6','美团账户','MT','VIRTUAL','0.00','RMB','美团总账户','0.00','0.00','Y',NULL,'1361','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('7','大众点评总账户','DZDP','VIRTUAL','0.00','RMB','大众点评团购支付部分','0.00','0.00','Y',NULL,'789','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('8','美团外卖账户','MTWM','VIRTUAL','0.00','RMB','美团外卖总账户','0.00','0.00','Y',NULL,'1129','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('9','美团外卖免单账户','FREE_MTWM','VIRTUAL','0.00','RMB','美团外卖商家免单部分','0.00','0.00',NULL,'8','796','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('10','支付宝账户','ALIPAY','VIRTUAL','0.00','RMB','支付宝总账户','0.00','0.00','Y',NULL,'829','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('11','商家免单总账户','FREE','CASH','0.00','RMB','商家线上线下免单总金额','0.00','0.00',NULL,NULL,'2551','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('12','美团超券账户','MT_SUPER','VIRTUAL','0.00','RMB','美团超券在线支付部分','0.00','0.00',NULL,'6','681','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('13','美团超券免单账户','FREE_MT_SUPER','VIRTUAL','0.00','RMB','美团超券商家免单部分','0.00','0.00',NULL,'6','406','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('14','大众点评闪慧账户','DPSH','VIRTUAL','0.00','RMB','大众点评闪惠支付部分','0.00','0.00',NULL,'7','497','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('15','POS机账户','POS','VIRTUAL','0.00','RMB','pos机总账户','0.00','0.00','Y',NULL,'768','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('16','商家在线免单账户','FREE_ONLINE','VIRTUAL','0.00','RMB','商家线上免单总金额','0.00','0.00',NULL,'11','3190','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('17','外卖超人账户','WMCR','VIRTUAL','0.00','RMB','外卖超人在线支付部分','0.00','0.00','Y',NULL,'120','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('18','外卖超人免单账户','FREE_WMCR','VIRTUAL','0.00','RMB','外卖超人商家免单部分','0.00','0.00',NULL,'17','98','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('20','百度糯米账户','BDNM','VIRTUAL','0.00','RMB','百度糯米总账户','0.00','0.00','Y',NULL,'60','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('21','派乐趣账户','PLQ','VIRTUAL','0.00','RMB','派乐趣总账户','0.00','0.00','Y',NULL,'111','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('22','派乐趣免单账户','FREE_PLQ','VIRTUAL','0.00','RMB','派乐趣商家免单部分','0.00','0.00',NULL,'21','91','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('23','淘点点总账户','TDD','VIRTUAL','0.00','RMB','淘点点总账户','0.00','0.00','Y',NULL,'0','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('24','饿了么免单账户','FREE_ELE','VIRTUAL','0.00','RMB','饿了么平台商家免单部分','0.00','0.00',NULL,'4','1576','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('25','美团免单账户','FREE_MT','VIRTUAL','0.00','RMB','美团团购商家免单部分','0.00','0.00',NULL,'6','35','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('26','美团外卖活动补贴账户','ALLOWANCE_MTWM','VIRTUAL','0.00','RMB','美团外卖平台返还给商家的补贴部分','0.00','0.00',NULL,'8','281','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('27','商家线下免单账户','FREE_OFFLINE','VIRTUAL','0.00','RMB','商家线下免单总金额','0.00','0.00',NULL,'11','19','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('28','百度糯米免单账户','FREE_BDNM','VIRTUAL','0.00','RMB','百度糯米商家免单部分','0.00','0.00',NULL,'20','26','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('29','百度糯米到店付账户','DDF_BDNM','VIRTUAL','0.00','RMB','百度糯米到店付部分','0.00','0.00',NULL,'20','0','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('30','百度糯米到店付免单账户','FREE_DDF_BDNM','VIRTUAL','0.00','RMB','百度糯米到店付免单部分','0.00','0.00',NULL,'20','0','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('31','派乐趣补贴账户','ALLOWANCE_PLQ','VIRTUAL','0.00','RMB','派乐趣平台返还给商家的补贴部分','0.00','0.00',NULL,'21','6','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('32','现金钱包账户','WALLET','CASH','0.00','RMB','现金钱包账户','0.00','0.00','Y',NULL,'0','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('33','支付宝免单账户','FREE_ALIPAY','VIRTUAL','0.00','RMB','支付宝在线免单部分','0.00','0.00',NULL,'10','11','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('34','大众点评闪惠免单账户','FREE_DPSH','VIRTUAL','0.00','RMB','大众点评闪惠商家免单部分','0.00','0.00',NULL,'7','3','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('35','大众点评团购免单账户','FREE_DPTG','VIRTUAL','0.00','RMB','大众点评团购商家免单部分','0.00','0.00',NULL,'7','0','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('36','外卖超人补贴账户','ALLOWNACE_WMCR','VIRTUAL','0.00','RMB','外卖超人平台返还商家补贴部分','0.00','0.00',NULL,'17','0','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('37','饿了么在线支付账户','ONLINE_ELE','VIRTUAL','0.00','RMB','饿了么在线支付金额入账','0.00','0.00',NULL,'4','1594','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('38','美团团购账户','ONLINE_MT','VIRTUAL','0.00','RMB','美团团购在线支付付账金额','0.00','0.00',NULL,'6','464','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('39','美团外卖在线支付账户','ONLINE_MTWM','VIRTUAL','0.00','RMB','美团外卖在线支付金额入账','0.00','0.00',NULL,'8','301','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('40','百度糯米团购账户','ONLINE_BDNM','VIRTUAL','0.00','RMB','百度糯米团购在线支付金额入账','0.00','0.00',NULL,'20','26','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('41','派乐趣在线支付账户','ONLINE_PLQ','VIRTUAL','0.00','RMB','派乐趣在线支付金额入账','0.00','0.00',NULL,'21','6','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('42','淘点点免单账户','FREE_TDD','VIRTUAL','0.00','RMB','淘点点商家免单金额','0.00','0.00',NULL,'23','0','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('43','淘点点在线支付账户','ONLINE_TDD','VIRTUAL','0.00','RMB','淘点点在线支付金额','0.00','0.00',NULL,'23','0','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('44','大众点评团购账户','ONLINE_DPTG','VIRTUAL','0.00','RMB','大众点评团购支付部分','0.00','0.00',NULL,'7','0','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('45','支付宝在线支付账户','ONLINE_ALIPAY','VIRTUAL','0.00','RMB','支付宝在线支付金额','0.00','0.00',NULL,'10','376','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('46','POS机免单账户','FREE_POS','VIRTUAL','0.00','RMB','POS机商家免单金额','0.00','0.00',NULL,'15','45','N');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('47','POS机在线支付账户','ONLINE_POS','VIRTUAL','0.00','RMB','pos刷卡部分','0.00','0.00',NULL,'15','159','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('48','百度外卖账户','BDWM','VIRTUAL','0.00','RMB','百度外卖主账户','0.00','0.00','Y',NULL,'59','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('49','百度外卖在线支付账户','ONLINE_BDWM','VIRTUAL','0.00','RMB','百度外卖在线支付金额','0.00','0.00',NULL,'48','59','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('50','百度外卖免单账户','FREE_BDWM','VIRTUAL','0.00','RMB','百度外卖商家免单金额','0.00','0.00',NULL,'48','0','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('51','百度外卖补贴账户','ALLOWANCE_BDWM','VIRTUAL','0.00','RMB','百度外卖平台给商家的补贴金额','0.00','0.00',NULL,'48','0','P');
insert into `bus_tb_account` (`accId`, `name`, `acc_no`, `type`, `balance`, `currency`, `description`, `earning_amount`, `expense_amount`, `is_parent`, `pid`, `version`, `symbol`) values('52','线上代金券使用账户','ONLINE_VOUCHER','VIRTUAL','0.00','RMB','商家自己在线上平台发放的代金券消费金额','0.00','0.00','Y',NULL,'0','N');
